server:
  port: 10002

spring:
  dubbo:
    scan: provider.service
    application:
      name: provider-B
    registry:
      address: zookeeper://127.0.0.1:2181
    protocol:
      name: dubbo
      port: 20882

