server:
  port: 10003

spring:
  dubbo:
    scan: provider.service
    application:
      name: provider-C
    registry:
      address: zookeeper://127.0.0.1:2181
    protocol:
      name: dubbo
      port: 20883

