server:
  port: 10001

spring:
  dubbo:
    scan: provider.service
    application:
      name: provider-A
    registry:
      address: zookeeper://127.0.0.1:2181
    protocol:
      name: dubbo
      port: 20880

