server:
  port: 10004

spring:
  dubbo:
    scan: provider.service
    application:
      name: provider-D
    registry:
      address: zookeeper://127.0.0.1:2181
    protocol:
      name: dubbo
      port: 20884

